text='   mEtODy MoDYFikoWAniA nAPiSów w PYthoNie '
print(text)
print(text.lower())
print(text.upper())
print(text.swapcase())
print(text.capitalize())
print(text.title())
print(text.lstrip())
print(text.rstrip())
print(text.replace(' ',':'))
print(text.splitlines())
print("!".join(text))
print(text[:10])
print(text[10:])
print(text[5:20])
print(text[7])
print(text[2])
